micronaut:
  security:
    authentication: idtoken
    token:
      jwt:
        enabled: true
        signatures.jwks.keycloak:
          url: ${SKEIN_CORE_JWKS:""}
    endpoints:
      login:
        enabled: false
    intercept-url-map:
      - pattern: /graphql
        access:
          - isAuthenticated()

datasources:
  default:
    enabled: true
    dialect: POSTGRES
    driverClassName: org.postgresql.Driver
    schema-generate: NONE
    db-type: postgresql
    minimumIdle: 0
    maximumPoolSize: 20
    reconnect: true

flyway:
  enabled: true
  datasources:
    default:
      enabled: true
